### ISSUE TITLE
run of demo: NOT accettable

### ISSUE THREAD

**Issue by ingconti** [Nugg7/TCPServer#1]
Ho letto il Red M, ma non va bene non è accettabile scaricarsi tutto in locale e poi far partire dopo averlo compilato. Devi fare in modo che chi lo scarica abbia un eseguibile funzionante

Un jar

**Comment by Nugg7** [comment]
added the jar executable file

**Comment by ingconti** [comment]
Does crash on my machine:


java.io.FileNotFoundException: Products.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at JSONManagerServer.<init>(JSONManagerServer.java:21)
	at Server.<clinit>(Server.java:15)
Server started!
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.json.simple.JSONObject.get(Object)" because "JSONManagerServer.doc" is null
	at JSONManagerServer.clearProducts(JSONManagerServer.java:60)
	at Server.main(Server.java:24)

did you try on linux ?
